services:
  laba-laba-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: laba-laba-app
    container_name: laba-laba-dev-app
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://ll_dev_user:ll_dev_db_pass@mysql:3306/ll_dev
      GIT_COMMIT: ${GIT_COMMIT:-unknown-compose}
    ports:
      - "10000:10000"
    volumes:
      - ./alembic:/src/alembic
    # uncomment if you don't want alembic to run before uvicorn
    #command: ["bash", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 10000"]


  mysql:
    image: mysql:8.0
    container_name: laba-laba-dev-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ll_dev_db_root_pass
      MYSQL_DATABASE: ll_dev
      MYSQL_USER: ll_dev_user
      MYSQL_PASSWORD: ll_dev_db_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
