FROM laba-laba-app

# Install extra test dependencies
COPY requirements-tests.txt /src/
RUN pip install -r ./requirements-tests.txt

COPY tests/ /src/tests/
COPY features/ /src/features/
COPY pytest.ini /src/

# Default command
CMD ["pytest", "tests/"]

