services:
  laba-laba-app:
    build: .
    container_name: laba-laba-dev-app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://ll_dev_user:ll_dev_db_pass@postgres/laba_laba_dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  postgres:
    image: postgres:16
    container_name: laba-laba-dev-db
    restart: always
    environment:
      POSTGRES_USER: ll_dev_user
      POSTGRES_PASSWORD: ll_dev_db_pass
      POSTGRES_DB: laba_laba_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
