FROM laba-laba-app

# Install extra test dependencies
COPY requirements-tests.txt /src/
RUN /root/.local/bin/uv pip install --system -r ./requirements-tests.txt

COPY pytest.ini /src/

# features/ and tests/ will be overlain in the dev.sh script

# Default command
CMD ["pytest", "tests/"]

