version: "3.8"

services:
  api:
    build: .
    container_name: fastapi-app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: crypto-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build: .
    container_name: test-runner
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - TEST_MODE=true
    command: pytest tests/

volumes:
  postgres_data:
