services:
  - type: web
    name: laba-laba-w3-app
    env: docker
    plan: free 
    branch: production
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
    dockerCommand: scripts/app_start_cmd.sh
