"""unique timestamp

Revision ID: 834029a52494
Revises: 8de476a1c506
Create Date: 2025-03-27 22:18:07.479097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834029a52494'
down_revision: Union[str, None] = '8de476a1c506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_timestamp_token', 'transactions', ['timestamp', 'token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_timestamp_token', 'transactions', type_='unique')
    # ### end Alembic commands ###
