# .github/workflows/automerge.yml
name: Auto Merge to Production

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

permissions:
  contents: write  
  pull-requests: write

jobs:
  automerge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Force push main → production
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          git checkout production
          git pull
          git merge main --ff-only
          git push origin production

