# .github/workflows/automerge.yml
name: Auto Merge to Production

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  automerge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Squash merge main → production
        uses: actions/github-script@v7
        with:
          script: |
            const main = 'main';
            const prod = 'production';

            const { data: prs } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${main}`,
              base: prod,
              state: 'open'
            });

            let pr;
            if (prs.length === 0) {
              const created = await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: main,
                base: prod,
                title: 'Auto PR: main → production',
                body: 'Automated squash merge after successful tests.'
              });
              pr = created.data;
            } else {
              pr = prs[0];
            }

            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'squash'
            });

            console.log(`Squash-merged PR #${pr.number} from main to production`);
