name: Run Tests

on:
  push:
    branches:
      - main
      - production
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make dev.sh executable
        run: chmod +x ./scripts/dev.sh

      - name: Build images
        run: ./scripts/dev.sh build

      - name: Run tests
        run: ./scripts/dev.sh tests

      - name: Run linter
        run: ./scripts/dev.sh lint
