name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make dev.sh executable
        run: chmod +x ./scripts/dev.sh

      - name: Run tests
        run: ./scripts/dev.sh tests
